-- This file is auto-generated by GenerateMusicAutoList.bat
-- Do not edit manually. Use music_overrides.csv to override labels.

EMP_MUSIC_AUTOLIST = {
    ["EMP_Onlap_CrawlingInTheDark"] = "Onlap - CrawlingInTheDark",
}
